version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Get the repo from GitHub
      - checkout

      # Find out where I am
      - run:
          command: ls

      # Install dependencies
      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt

      # Run tests
      - run:
          name: run tests
          command: |
            pytest test_getjsondata.py
